USE [master]
GO
/****** Object:  Database [AngularMVCDb]    Script Date: 01/10/2014 22:20:12 ******/
CREATE DATABASE [AngularMVCDb]
 CONTAINMENT = NONE
 
ALTER DATABASE [AngularMVCDb] SET COMPATIBILITY_LEVEL = 120
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [AngularMVCDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [AngularMVCDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [AngularMVCDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [AngularMVCDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [AngularMVCDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [AngularMVCDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [AngularMVCDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [AngularMVCDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [AngularMVCDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [AngularMVCDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [AngularMVCDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [AngularMVCDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [AngularMVCDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [AngularMVCDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [AngularMVCDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [AngularMVCDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [AngularMVCDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [AngularMVCDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [AngularMVCDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [AngularMVCDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [AngularMVCDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [AngularMVCDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [AngularMVCDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [AngularMVCDb] SET RECOVERY FULL 
GO
ALTER DATABASE [AngularMVCDb] SET  MULTI_USER 
GO
ALTER DATABASE [AngularMVCDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [AngularMVCDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [AngularMVCDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [AngularMVCDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [AngularMVCDb] SET DELAYED_DURABILITY = DISABLED 
GO
EXEC sys.sp_db_vardecimal_storage_format N'AngularMVCDb', N'ON'
GO
USE [AngularMVCDb]
GO
/****** Object:  Table [dbo].[Site]    Script Date: 01/10/2014 22:20:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Site](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Url] [nvarchar](500) NULL,
	[Note] [nvarchar](max) NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK_Site] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Tag]    Script Date: 01/10/2014 22:20:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tag](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](150) NULL,
	[Date] [date] NULL,
 CONSTRAINT [PK_Tag] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[TagSite]    Script Date: 01/10/2014 22:20:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TagSite](
	[SiteId] [int] NOT NULL,
	[TagId] [int] NOT NULL,
 CONSTRAINT [PK_TagSite] PRIMARY KEY CLUSTERED 
(
	[SiteId] ASC,
	[TagId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
/****** Object:  Index [IX_Tag]    Script Date: 01/10/2014 22:20:12 ******/
CREATE UNIQUE NONCLUSTERED INDEX [IX_Tag] ON [dbo].[Tag]
(
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[TagSite]  WITH CHECK ADD  CONSTRAINT [FK_TagSite_Site] FOREIGN KEY([SiteId])
REFERENCES [dbo].[Site] ([Id])
GO
ALTER TABLE [dbo].[TagSite] CHECK CONSTRAINT [FK_TagSite_Site]
GO
ALTER TABLE [dbo].[TagSite]  WITH CHECK ADD  CONSTRAINT [FK_TagSite_Tag] FOREIGN KEY([TagId])
REFERENCES [dbo].[Tag] ([Id])
GO
ALTER TABLE [dbo].[TagSite] CHECK CONSTRAINT [FK_TagSite_Tag]
GO
USE [master]
GO
ALTER DATABASE [AngularMVCDb] SET  READ_WRITE 
GO
